### ISSUE TITLE
Cancel on<Action> job when surrounding inState condition doesn't anymore

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#128]
At the moment we don't cancel any ongoing handler of a `on<Action>` if the surrounding `inState<State>` condition doesn't hold anymore (so statemachine transitioned to another state).

This was actually the expected behavior before FlowRedux 0.5.0, but now should change.

**Comment by gabrielittner** [comment]
Doesn't this test mean that we do cancel? https://github.com/freeletics/FlowRedux/blob/main/dsl/src/commonTest/kotlin/com/freeletics/flowredux/dsl/OnActionTest.kt#L48 If we wouldn't cancel during the delay then `reached` would be `true`. Is there some other case where we don't cancel?
