### ISSUE TITLE
Add support for Effects that dont change state

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#129]
At the moment you cannot do a piece of work without the need of returning a `ChangeState` object.

This proposal is about adding "effects". A typical use case for an  Effect is triggering navigation without changing the state of the statemachine itself or doing some analytics tracking calls.

Proposed Syntax
```kotlin
inState<MyState> {
  onEnterEffect { stateSnapshot : MyState ->
       // Do something.
       Unit // return unit, no state change
   }

  onActionEffect<MyAction> action : MyAction, stateSnapshot : MyState ->
       // Do something.
       Unit // return unit, no state change
   }

  collectWhileInStateEffect(flowOf(1,2)) { value : Int, 
stateSnapshot : MyState ->
       // Do something.
       Unit // return unit, no state change
   }
}
```

Specs:
- Effects are suspending: i.e. signature lambda for `onEnterEffect ` is `suspend (State) -> Unit`
- Effects dont get canceled when state transition happening.
- Effects are per default canceled when StateMachine  CoroutineScope gets canceled. If you want to escape you can always use `withContext(NonCancelable)`

**Comment by gabrielittner** [comment]
Why do we need the explicit `Unit` that the effect returns?

**Comment by sockeqwe** [comment]
@gabrielittner you mean why it would not just return `Any?` instead of `Unit` or what do you mean exactly?

**Comment by gabrielittner** [comment]
More like, why does the lambda need to return anything at all?

**Comment by sockeqwe** [comment]
Hm, maybe I misunderstand you but what is the signature of such a lambda? What would you propose (can you give an example)?

**Comment by gabrielittner** [comment]
The signature would still be `fun onEnterEffect(effect: (stateSnapshot : MyState) -> Unit)`, but the usage like this
```
onEnterEffect { stateSnapshot : MyState ->
   // Do something.
   // no Unit here
}
```

Effectively the same, I guess I was just confused by the explicit `Unit` as last line in your examples.

**Comment by sockeqwe** [comment]
👍  got it. Then we are talking about the same thing
