### ISSUE TITLE
Cleanup sample code

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#132]
The sample is old and has a lot of unused dependencies like ktor or screenshot testing. We don't need that. Let's remove it as it just causes noise and  confusion.

**Comment by rasfarrf5** [comment]
Hi sockeqwe,
I would like to contribute this issue. 

Can you please explain what need to do? Remove entire ktor usage?

**Comment by sockeqwe** [comment]
Hi @rasfarrf5,
Thanks for offering help, highly appreciated!

Unfortunately or fortunately it looks like @gabrielittner already did most of the cleanup already at least for the shared code of the multiplatform sample.
 
https://github.com/freeletics/FlowRedux/commit/22fe9f802fb104adb440296c5f5f8b0ecadb15f0

Remaining are mainly cleaning up there android sample `build.gradle` file
https://github.com/freeletics/FlowRedux/blob/main/sample/android/build.gradle

a lot of dependencies are not used at all, i.e. all http stuff (ktor, okhttp, Moshi) is not needed, some testing libraries like screengrab are not used as well, some dependencies could be updated to latest version like fragments etc.
Do going over that file and remove everything unused (just trying that code still compiles) and update remaining dependencies to latest version would be helpful. What do you think?

**Comment by rasfarrf5** [comment]
Sure will work on it to clean up libs. 😊

**Comment by rasfarrf5** [comment]
Changes are done and pushed for verification. Thanks

**Comment by sockeqwe** [comment]
Thank you @rasfarrf5  for your contribution!

It's merged now 
https://github.com/freeletics/FlowRedux/pull/145
