### ISSUE TITLE
Rethink Logging

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#135]
At the moment a `FlowReduxLogger` is passed in as a constructor parameter and it logs things.

The Api are awful, nor is it clear what the logger is good for and what it o is suppose to log (i.e. internal ro debug state machine? For FlowRedux maintainers to create bug reports? For consumer of FlowRedux library)?

**Comment by gabrielittner** [comment]
For the DSL in regards to what should be logged: I think it would make sense to not pass the logger up to `reduxStore` and instead have more specific logging in the individual side effects builders and the reducer.
