### ISSUE TITLE
Build for javascript

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#138]

**Comment by NorbertSandor** [comment]
Is there a plan to implement JS support?

**Comment by hoc081098** [comment]
Will adding target `js { nodejs() }` fix this issue?

**Comment by NorbertSandor** [comment]
I would like to use this library with Compose/Web...

**Comment by gabrielittner** [comment]
There is a snapshot build that has `js-SNAPSHOT` as version available now https://oss.sonatype.org/content/repositories/snapshots/com/freeletics/flowredux/flowredux/js-SNAPSHOT/ This should generally work and it would be cool if you could give it a try. For js there is 1 failing test and 2 tests that I had to comment out, but in all cases it's more about the test itself and not really about something being broken.

**Comment by gabrielittner** [comment]
New snapshot with js support is available `com.freeletics.flowredux:flowredux:js-SNAPSHOT`. All tests are passing now so this should be fully working. I expect this to land in the next release which should happen shortly after coroutines 1.7.0 is stable.
