### ISSUE TITLE
Inconsistency between collectWhileIn(Any)State and on

### ISSUE THREAD

**Issue by gabrielittner** [freeletics/FlowRedux#162]
As an example let's say we have this state
```
sealed class MyState
class StateA : MyState()
class StateB : MyState()
```

Now in a state machine for `MyState` you can do
```
init {
    spec {
        collectWhileInAnyState(...) { ... }
        
        inState<MyState> {
            collectWhileInState(...) { ... }
            on<...>() { ... }
        }
    }
}
```

The 2 `collectWhile...` calls have the same lifetime because we are always in `MyState`. The inconsistency in my opinion is that there are effectively 2 ways to do `collectWhileInAnyState` but it's only possible to define an `on` that should happen in any state within `inState`. Initially I was searching for an `onInAnyState` because I knew `collectWhileInAnyState` exists. 

Instead of having `collectWhileInAnyState` could we just remove it and recommend using `collectWhileInState` with the base class? Then it's consistent with `on` and there is just one way to do things.

**Comment by sockeqwe** [comment]
As agreed on in our call: we will remove `collectWhileInAnyState`
