### ISSUE TITLE
Set up ktlint

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#187]
To help to lint and format our codebase we would like to add [ktlint](https://github.com/pinterest/ktlint) to this project.

**Comment by mcatta** [comment]
Hi, I can help you with this issue because I have recently set up ktlint on my company's project. I'm thinking of adding the validation as a stage on the `build` workflow, do you have any specific requirements for that.? Do we want something also in pre-commit?

Marco

**Comment by gabrielittner** [comment]
Hey, I don't think we need a pre-commit hook, it would be enough to add something to ci like you mentioned and having a way to run the formatter manually locally.
