### ISSUE TITLE
Add targets for Apple Silicon

### ISSUE THREAD

**Issue by ychescale9** [freeletics/FlowRedux#199]
Kotlin 1.5.30 added [native support for Apple Silicon](https://kotlinlang.org/docs/whatsnew1530.html#apple-silicon-support).

To enable this in a KMP project (app) all transitive dependencies need to add those new targets.

Upcoming [kotlinx.coroutines 1.5.2 will be adding these](https://github.com/Kotlin/kotlinx.coroutines/pull/2904/files):
```
 addTarget(presets.iosSimulatorArm64)
 addTarget(presets.watchosSimulatorArm64)
 addTarget(presets.tvosSimulatorArm64)
 addTarget(presets.macosArm64)
```

It'd be great to add these targets to `FlowRedux` too.

Happy to send a PR once Coroutines 1.5.2 is out :)

**Comment by sockeqwe** [comment]
sounds great, PR is very welcome! 

(minor dependency to compose to support 1.5.30)
