### ISSUE TITLE
enable coroutine multi-threaded for ntaive targets

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#264]
Right now mutlithreaded coroutine dont work on native targets.

**Comment by gabrielittner** [comment]
The native-mt artifact will not be released anymore from 1.7 on https://github.com/Kotlin/kotlinx.coroutines/issues/462#issuecomment-999557659 so we should focus on testing if FlowRedux works with the new memory model without any changes

**Comment by sockeqwe** [comment]
👍 good to know

**Comment by gabrielittner** [comment]
The new memory model is stable, there is nothing left for us to do here.
