### ISSUE TITLE
Change the DSL artifact to be the main artifact, make reduxStore internal

### ISSUE THREAD

**Issue by gabrielittner** [freeletics/FlowRedux#270]
I've been wondering whether "FlowRedux" should just be the DSL artifact and the `reduxStore` is just an internal implementation detail. That would also allow us significantly change the implementation later on (like #209) without having to maintain the `reduxStore` method.

**Comment by sockeqwe** [comment]
Agreed, no objections from my side to change that!

Gabriel Ittner ***@***.***> schrieb am Fr., 11. März 2022,
13:32:
