### ISSUE TITLE
State machine suspend invoke function in state

### ISSUE THREAD

**Issue by Jparrgam** [freeletics/FlowRedux#295]
Hi, I made the changes as you advised me, but I have a problem when I make an http call, I'm getting a courutine is canceled error, I share my code with you 

state machine

``` Kotlin
spec {
            inState<LoadingState> {
                on<GetQuestionsAction> { action, _ ->
                    Log.e(
                        "ComplianceMachineState",
                        "LoadingState GetQuestionsAction: ${action.country}"
                    )
                    OverrideState(GetQuestionsAnswerState(action.country))
                }
            }

            inState<GetQuestionsAnswerState> {
                onEnter { state ->
                    Log.e(
                        "ComplianceMachineState",
                        "GetQuestionsAnswerState"
                    )
                    try {
                        val result = complianceQuestionsUseCase(state.country) //suspend function call return error kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@b74dc27
                        if (result is UIState.UnExpectedError) {
                            OverrideState(GetQuestionsAnswerErrorState(state.country))
                        } else {
                            OverrideState(AnswerShowContentState())
                        }
                    } catch (e: Exception) {
                        OverrideState(GetQuestionsAnswerErrorState(state.country))
                    }
                }
            }

            inState<AnswerShowContentState> {
                onEnter {
                    Log.e("ComplianceMachineState", "AnswerShowContentState")
                    NoStateChange
                }
            }

            inState<GetQuestionsAnswerErrorState> {
                onEnter { state ->
                    Log.e(
                        "ComplianceMachineState",
                        "GetQuestionsAnswerErrorState onEnter: ${state.country}"
                    )
                    OverrideState(GetQuestionsAnswerState(state.country))
                }
            }
        }
```

prints logs, no enter in GetQuestionsAnswerErrorState

2022-05-02 13:36:09.593 3080                                                              E  LoadingState GetQuestionsAction: co
2022-05-02 13:36:13.471 3080                                                               E  GetQuestionsAnswerState

my composable 

``` Kotlin
@Composable
fun TestFlowReduxStateMachine(
    stateMachine: ComplianceMachineState,
) {
    val (state, dispatchAction) = stateMachine.rememberStateAndDispatch()


    LaunchedEffect(Unit) {
        dispatchAction(GetQuestionsAction("CO"))
    }
}
```

onEnter coroutine call complianceQuestionsUseCase is cancelled

_Originally posted by @Jparrgam in https://github.com/freeletics/FlowRedux/issues/294#issuecomment-1115129056_

**Comment by sockeqwe** [comment]
Hm, your FlowRedux code looks alright. So either is the compose part (which starts the coroutine and statemachine) the root error cause or `complianceQuestionsUseCase`.

Regarding the compose code: you don't need to wrap dispatch (action) calls into `LaunchEffect`. Just invoke   `dispatchAction(GetQuestionsAction("CO"))` directly without the `LaunchEffect` around it. Please keep in mind that recomposition of your composable could happen all the time. 

If thay doesn't help:

```kotlin
fun TestFlowReduxStateMachine(
    stateMachine: ComplianceMachineState // this seem to me problematic
) {...}
```
I'm not 100 percent sure but passing the state machine could be problematic. Could it be that the parent Composable that calls `TestFlowReduxStateMachine()` recreates a new state machine instance on recomposition?

Could you try to create the statemachine inside `TestFlowReduxStateMachine()` (so not passing it as a parameter) to see if this changes anything?

If that all doesn't help:
Could it be that something is not working as expected with `complianceQuestionsUseCase()`? What is it doing? Can you share that code as well? Or what happens if you call this `complianceQuestionsUseCase()` directly from a coroutine (something like `launch { complianceQuestionsUseCase() }`, so not inside your FlowReduxStateMachine, really just execut your use case from within : What does happen? any exception?

**Comment by Jparrgam** [comment]
> Hm, your FlowRedux code looks alright. So either is the compose part (which starts the coroutine and statemachine) the root error cause or `complianceQuestionsUseCase`.
> 
> Regarding the compose code: you don't need to wrap dispatch (action) calls into `LaunchEffect`. Just invoke `dispatchAction(GetQuestionsAction("CO"))` directly without the `LaunchEffect` around it. Please keep in mind that recomposition of your composable could happen all the time.
> 
> If thay doesn't help:
> 
> ```kotlin
> fun TestFlowReduxStateMachine(
>     stateMachine: ComplianceMachineState // this seem to me problematic
> ) {...}
> ```
> 
> I'm not 100 percent sure but passing the state machine could be problematic. Could it be that the parent Composable that calls `TestFlowReduxStateMachine()` recreates a new state machine instance on recomposition?
> 
> Could you try to create the statemachine inside `TestFlowReduxStateMachine()` (so not passing it as a parameter) to see if this changes anything?
> 
> If that all doesn't help: Could it be that something is not working as expected with `complianceQuestionsUseCase()`? What is it doing? Can you share that code as well? Or what happens if you call this `complianceQuestionsUseCase()` directly from a coroutine (something like `launch { complianceQuestionsUseCase() }`, so not inside your FlowReduxStateMachine, really just execut your use case from within you own coroutine) : What does happen? any exception?

**Comment by sockeqwe** [comment]
Glad it worked out. 
If you really want to pass stateMachine as parameter you need to tell compose that this state machine object never changes. 
you probably need to add `@Immutable` or  `@Stable` annotation to your FlowReduxStateMachine to provide this information to Compose.
https://stackoverflow.com/questions/68575936/what-does-mean-stable-and-immutable-annotation-in-jetpack-compose

However, I would still advise against passing StateMachines as parameter around. Passing the state to render it to UI and passing the `dispatch(action)` function to children is totally fine (and designed to do so)
