### ISSUE TITLE
Additional condition for `on<Action>` construct

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#311]
We already have `inState<S>(additionalCondition = { ... })` and maybe it would be useful to add `additionalCondition` also to `on<Action>`.

Use case:
https://github.com/freeletics/FlowRedux/blob/1387be5bc2ee32c3c36c2d33f40b3f95e4dd71fb/sample/shared_code/src/commonMain/kotlin/com/freeletics/flowredux/sample/shared/MarkAsFavoriteStateMachine.kt#L51-L59

Where the `on<Action>` block should  actually only be triggered when `action.id == someId`

Just leaving it here for a potential future addition / improvement.

**Comment by gabrielittner** [comment]
Wouldn't it be better to have the check inside the method for testability?

**Comment by gabrielittner** [comment]
@sockeqwe Any objections against closing this since we are adding the condition block and also are deprecating the additional condition overload from `isInState`?

**Comment by sockeqwe** [comment]
Yep, sounds good!

Gabriel Ittner ***@***.***> schrieb am Mi., 31. Mai 2023,
03:45:
