### ISSUE TITLE
Using FlowRedux in Jetpack Compose with MVVM pattern

### ISSUE THREAD

**Issue by masterj3y** [freeletics/FlowRedux#391]
How to dispatch an `action` immediately while navigating to a screen where it needs to fetch the data by a dynamic parameter?

State Machine is instantiated inside the View Model:
```@HiltViewModel
class SubtitlesViewModel @Inject constructor(
    private val stateMachine: SubtitleStateMachine,
    @ViewModelCoroutineDispatcher
    private val coroutineDispatcher: CoroutineDispatcher
) : ViewModel() {

    val state = stateMachine.state
        .stateIn(
            viewModelScope + coroutineDispatcher,
            SharingStarted.Lazily,
            null
        )

    fun dispatch(action: MovieDetailsAction) {
        viewModelScope.launch(coroutineDispatcher) { stateMachine.dispatch(action) }
    }
}
```

when the user navigates to that screen, it immediately dispatches the corresponding action:
```
@Composable
fun MovieDetails(
    moviePath: String?, viewModel: SubtitlesViewModel = hiltViewModel(), onUpClick: () -> Unit
) {

    val state by rememberStateWithLifecycle(stateFlow = viewModel.state)

    LaunchedEffect(Unit) {
        if (!moviePath.isNullOrBlank())
            viewModel.dispatch(MovieDetailsAction.LoadMovieDetails(moviePath))
    }
}
```
but it throws an exception:
`java.lang.IllegalStateException: Cannot dispatch action github.masterj3y.subtitle.ui.details.MovieDetailsAction$LoadMovieDetails@6f88528 because state Flow of this FlowReduxStateMachine is not collected yet. Start collecting the state Flow before dispatching any action.`

an temporary workaround is:

```
val state by rememberStateWithLifecycle(stateFlow = viewModel.state)

LaunchedEffect(state) {
   if (state !is MovieDetailsState.Loading)
      return@LaunchedEffect

      if (!moviePath.isNullOrBlank())
         viewModel.dispatch(MovieDetailsAction.LoadMovieDetails(moviePath))
}
```

is there a better way to fix it?

**Comment by hoc081098** [comment]
Try `SharingStarted.Early`

**Comment by masterj3y** [comment]
Doesn't work.

**Comment by hoc081098** [comment]
Try using `CompletableDeferred`

```kotlin

val state =   stateMachine.state .stateIn( viewModelScope + coroutineDispatcher, SharingStarted.Lazily, null ) fun dispatch(action: MovieDetailsAction) 

```

**Comment by sockeqwe** [comment]
I think the workaround suggested by @hoc081098  will work.


Another question that I have when looking at your code example:

```kotlin
if (!moviePath.isNullOrBlank())
         viewModel.dispatch(MovieDetailsAction.LoadMovieDetails(moviePath))
```

It sounds like you would like to "force" the statemachine into a certain state by dispatching `LoadMovieDetails`. But I am wondering if this is not something that should be modeled inside the FlowReduxStateMachine specification actually. That would be more idiomatic. then you could avoid the problem of dispatching before collecting state at all.

**Comment by gabrielittner** [comment]
Another solution is to check whether the `state` is not null before you do anything in compose since you are using that as initial value for `stateIn`. That way you ensure that the state machine started running. 

I agree with Hannes though, this seems generally like something that you can completely solve without the action. What we usually do is to have our loading state as initial state for the state machine and then load the data in `onEnter`. That way it will start automatically when the state machine starts.

I'm closing the issue as there is nothing on the flow redux side to do, but happy to continue the conversation
