### ISSUE TITLE
Make Compose artifact Compose Multiplatform

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#395]
At the moment the compose artifact is not targeting compose multiplatform and therefore not usable in compose desktop or compose web. 

A nice enhancement would be to support compose multiplatform for the `:compose` artifact of FlowRedux. Just copy & pasting the `rememberStateAndDispatch()` function definition into compose desktop/web applications is what I do right now (and it works without any modification). Would be nice to have this supported by FlowRedux directly.

**Comment by gabrielittner** [comment]
Would making it a multiplatform module with JVM and android targets work? Common could have a compileOnly dependency on compose and then the 2 platform targets real dependencies on Google/Jetbrains compose
