### ISSUE TITLE
ChangedState reduce() type mismatch

### ISSUE THREAD

**Issue by dzinek** [freeletics/FlowRedux#469]
According to [Unit testing handlers](https://freeletics.github.io/FlowRedux/dsl/#unit-testing-handlers) I want to test my state logic.

```
    @Test
    fun loadMyObjectsAndMoveToContentOrError() = runTest {
        val startState = State(Loading)
        val changedState : ChangedState<MyObjectListState> = stateMachine.loadMyObjectsAndMoveToContentOrError(startState)

        val myObjectList = listOf(
            myObject,
            myObject.copy(id = 1),
            myObject.copy(id = 2)
        )

        val actual : MyObjectListState = changedState.reduce(startState)

        val expected = ContentState(myObjectList)
        assertThat(actual).isEqualTo(expected)
    }
```

But I have issues with `.reduce()` extension:
* in `val actual : MyObjectListState = changedState.reduce(startState)` line Android Studio throws an error with `Type mismatch. Required: LockObjectListState. Found: State<LockObjectListState.Loading>`
* when I removed type declaration and leave it as `Any` or when I cast it with `as LockObjectListState` I got an error from running test - `class com.freeletics.flowredux.dsl.State cannot be cast to class com.foo.myobject.ui.state.MyObjectListState$Loading (com.freeletics.flowredux.dsl.State and com.foo.myobject.ui.state.MyObjectListState$Loading are in unnamed module of loader 'app')`

I have a standard state:
```
sealed interface MyObjectListState {
    object Initial : MyObjectListState

    object Loading : MyObjectListState

    data class ContentState(
        val list: List<MyObject> = emptyList(),
    ) : MyObjectListState

    data class Error(val e: Throwable) : MyObjectListState
}
```
and DSL for StateMachine:
```
    init {
        spec {
            inState<Loading> {
                onEnter { state: State<Loading> ->
                    loadMyObjectsAndMoveToContentOrError(state)
                }
            }
            inState<ContentState> {
                on { action: ToggleFavorite, state: State<ContentState> ->
                    toggleFavoriteAndReplaceObjectContent(action, state)
                }
            }
        }
    }
```

`loadMyObjectsAndMoveToContentOrError(state)` function looks like:
```
    suspend fun loadMyObjectsAndMoveToContentOrError(
        state: State<Loading>
    ) : ChangedState<MyObjectListState> {
        return try {
            val myObjects = getMyObjects()
            state.override { ContentState(myObjects) }
        } catch (t: Throwable) {
            state.override { Error(t) }
        }
    }
```

**Comment by gabrielittner** [comment]
Does this work for you `val actual : MyObjectListState = changedState.reduce(startState.snapshot)`?

**Comment by dzinek** [comment]
It works, thanks a lot.
So I propose change in docs - https://github.com/freeletics/FlowRedux/pull/474

**Comment by gabrielittner** [comment]
Good to hear that it works and thank you for fixing the docs
