### ISSUE TITLE
DSL: Add a way to work with"Identity" of states

### ISSUE THREAD

**Issue by sockeqwe** [freeletics/FlowRedux#480]
Following up on #479 it would be convenient to express staying in a certain state as long as the "identity" of a state did not change  (in addition to what we already have as DSL; this is not about removing existing DSL functionality)

Let's discuss here some ideas how we could make that happening:

## Proposal 1: Keep existing dsl and add a `withIdentity { ... }` block:

```kotlin
inState<State>  {
    on<Action> {...} // stay as it is
    onEnter {...} // stay as it is
    collectWhileInState {...} // stay as it is
    onEnterStartStateMachine { ... } // stay as it is
    onActionStartStateMachine { ... } // stay as it is

    withIdentity( identity = { state -> state.id }) {  // new DSL Block. It keeps track of whenever state's identity change
            onEnter {...} // same functionality as usual
            collectWhileInState {...} // same functionality as usual
            onEnterStartStateMachine { ... } // stay as it is

            // I think on<Action> and onActionStartStateMachine should not be part of the withIdentity block
     }
}
```
Something like the one above  👆  should be doable without breaking changes and stay backward compatible. 
Some more thoughts: 
- `withIdentity`: Probably there are better names, something like `onIdentityChanged` or something else.
- I am not sure if `Action` related DSL constructs should be part of the `withIdentity` block. I am not sure if withIdentity and Action  work well together. 
 

We could also think a bit broader and do some (breaking changes) with `inState( additionalCondition = { ... })`: Maybe something like this:

```kotlin
inState<State> { // no additionalCondition as parameter here
    on<Action> {...} // stay as it is
    onEnter {...} // stay as it is
    collectWhileInState {...} // stay as it is
    onEnterStartStateMachine { ... } // stay as it is
    onActionStartStateMachine { ... } // stay as it is

    // NEW
    condition( { state ->  .... }) {
        on<Action> {...} // stay as it is
        onEnter {...} // stay as it is
        collectWhileInState {...} // stay as it is
        onEnterStartStateMachine { ... } // stay as it is
        onActionStartStateMachine { ... } // stay as it is

        // should we allow nested conditions?
        condition( { state ->  .... }) {
           on<Action> {...} // stay as it is
           onEnter {...} // stay as it is
           collectWhileInState {...} // stay as it is
           onEnterStartStateMachine { ... } // stay as it is
           onActionStartStateMachine { ... } // stay as it is

           // Nested condition
           condition( { state -> ... } ) {
              ...
           }
       }
    }
   
    // NEW
    withIdentity( identity = { state -> state.id }) {  // new DSL Block. It keeps track of whenever state's identity change
            onEnter {...} // same functionality as usual
            collectWhileInState {...} // same functionality as usual
            onEnterStartStateMachine { ... } // stay as it is

            // I think on<Action> and onActionStartStateMachine should not be part of the withIdentity block
     }    
}

// generic inStateWithCondition stays as it is
inStateWithCondition { 
      condition( { state ->  .... }) { ... } 
      withIdentity( identity = { state -> state.id })
}
```

What do you think @gabrielittner ?

**Comment by gabrielittner** [comment]
In #310 where you suggested the condition block I was more leaning towards having overloads of `inState` (`inState<T>`, `inState<T>(additionalCondition = {})`) and allowing `inState` inside another, but now I'm more leaning towards your suggestion here to have condition and indentity as nested blocks. They should be better for readability, I sometimes missed the current `additionalCondition = { ... }` and was wondering for a moment why there are repeated `inState` blocks.

> I think on<Action> and onActionStartStateMachine should not be part of the withIdentity block
Yes, makes sense

> should we allow nested conditions?
My first impulse was why not, but lets start without them. Too much nesting hurts readability.

> generic inStateWithCondition stays as it is

Couldn't we have the new `condition` and `withIdentity` methods also on this level and get rid of this special `inStateWithCondition` (tbh I forgot that it exists).



I'll think a bit more about what should be possible to nest and what should be available on what level, this brought up a bunch of questions in my head:
- Should everything that is available inside `inState` also be available on the top level? Currently global actions or collectWhileInState can be solved with `inState<TopLevelParentState>`. Having it a the top level makes the DSL more comlicated but it also makes the hierarchy clearer.
- If no, should `inStateWithCondition` still be removed/deprecated because you can now also do `inState<TopLevelParentState> { condition({ .. .}) { ... }`?
- If yes, should we also allow putting `inState` inside `inState` to better show deeper type hierarchies (spec would effectively be an `inState<TopLevelParentState>` then)? Downside would be the risk of too much nesting.
- What about combinations of `withIdentity` and `condition`? Probably leave this out until there are use cases, also `condition` could still be handled inide the `on...` implementation, so it's not a blocker in any case.

(None of these questions would be a blocker to adding `condition` and `withIdentity` to `InStateBuilderBlock` since they are more about the things around it that can be changed separately)

**Comment by sockeqwe** [comment]
Ok, then I think we have a plan around `withIdentity` (I still think a better and more expressive name is needed but let's think about that later. maybe something like `untilIdentityChanged` ... )

Regarding `condition` block:

> Should everything that is available inside inState also be available on the top level? Currently global actions or collectWhileInState can be solved with inState<TopLevelParentState>. Having it a the top level makes the DSL more complicated but it also makes the hierarchy clearer.

I dont fully understand. but I would keep "Top Level DSL blocks as it is now" (`onEnter` `onAction` and `collectWhileInState`, `onEnterStartStatemachine`, `onActionStartStateMachine`)  and just add the possibilities to also add  `condition` and `withIdentity` that then can have again all the "Top Level DSL blocks" again (`onEnter` `onAction` and `collectWhileInState`, `onEnterStartStatemachine`, `onActionStartStateMachine`).


So I would sum it up to something like this:

```kotlin
inState<State> {
  onEnter { ... }
  onAction { ... }
  collectWhileInState { ... }
  onEnterStartStateMachine { ... }
  onActionStartStateMachine { ... }
  
  condition({ state ->  ... } ) {
      onEnter { ... }
      onAction { ... }
      collectWhileInState { ... }
      onEnterStartStateMachine { ... }
      onActionStartStateMachine { ... }
      
      withIdentity { ... } // see bellow
      
      // No nested condition { ... } block inside a condition for now (until we have a good use case for it).
  }  
  
  withIdentity({ state -> ... }) {
      onEnter { ... }
      onAction { ... }
      collectWhileInState { ... }
      onEnterStartStateMachine { ... }
      onActionStartStateMachine { ... }    // I originally thought of not having onActionStartStateMachine as part of withIdentity, but now I dont see a reason why not having it
  }

} 
```

> If no, should inStateWithCondition still be removed/deprecated because you can now also do inState<TopLevelParentState> { condition({ .. .}) { ... }?

Yes I would remove `inStateWithCondition`. So it is a  breaking change IMHO, and I am not sure if we need backwards compatibility for this (I assume it is mainly used inside Freeletics only, so we could go with FlowRedux 2.0 or just make a breaking change as FlowRedux 1.1.0. I lean more towards 1.1.0).

> What about combinations of withIdentity and condition? Probably leave this out until there are use cases, also condition could still be handled inside the on... implementation, so it's not a blocker in any case.

I would give `condition` priority over `withIdentity`. So `condition` can have a `withIdentityBlock` inside but not the other way around:

```kotlin
// ALLOWED BY DSL:
condition( {state -> ... } { 
   withIdentitiy((state -> ... }) { ... }
}

// NOT ALLOWED BY DSL
withIdentitiy((state -> ... }) {
   condition( {state -> ... } {  ... }
}
```


What do you think?

**Comment by gabrielittner** [comment]
> `untilIdentityChanged`

That one sounds good to me.

> Open Question for me is: Can there be multiple withIdentity blocks (regardless of whether it is in inState directly or in condition block. I tend to limit it to only 1 withIdentity block for each inState and each condition block. If we want to limit it to 1 block only, then I think technically we can only check that at runtime (or maybe with some Lint Rules at compile time?)

I think one makes sense, but yes it would be a runtime plus a potential lint check.


So I think for this issue what we do is:
1. add `condition` to `inState`, same methods as `inState` except for the `condition` method itself
2. add `untilIdentityChanged` to `inState` and `condition`, does not have action related methods, no `condition` method and no nesting, limited to 1
3. deprecate `inStateWithCondition` 


--------------------------------

For the not directly related parts:

> I dont fully understand. but I would keep "Top Level DSL blocks as it is now" (onEnter onAction and collectWhileInState, onEnterStartStatemachine, onActionStartStateMachine) and just add the possibilities to also add condition and withIdentity that then can have again all the "Top Level DSL blocks" again (onEnter onAction and collectWhileInState, onEnterStartStatemachine, onActionStartStateMachine).

With top level I meant at the same level that we have `inState`. So let's say your state is like 
this 
```
sealed interface Parent
sealed interface Intermediate : Parent
object Child1 : Intermediate
object Child2 : Intermediate
object Child3 : Parent
```
Right now you can do this:
```
spec {
    // global things
    inState<Parent> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
    // things shared between child1 and child2
    inState<Intermediate> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
    // child specific things
    inState<Child1> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
    inState<Child2> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
    inState<Child3> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
}
```

What we could potentially have to show the type hierarchy better would be:
```

spec {
    // global things
    onEnter { ... }
    onAction { ... }
    collectWhileInState { ... }
    onEnterStartStateMachine { ... }
    onActionStartStateMachine { ... }
    condition { ... }
    untilIdentityChanged { ... }

    // things shared between child1 and child2
    inState<Intermediate> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
    // child specific things
    inState<Child1> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
    inState<Child2> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
    inState<Child3> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
}
```
Or even:
```
spec {
    // global things
    onEnter { ... }
    onAction { ... }
    collectWhileInState { ... }
    onEnterStartStateMachine { ... }
    onActionStartStateMachine { ... }
    condition { ... }
    untilIdentityChanged { ... }

    // things shared between child1 and child2
    inState<Intermediate> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }

        // child specific things
        inState<Child1> {
            onEnter { ... }
            onAction { ... }
            collectWhileInState { ... }
            onEnterStartStateMachine { ... }
            onActionStartStateMachine { ... }
            condition { ... }
            untilIdentityChanged { ... }
        }
        inState<Child2> {
            onEnter { ... }
            onAction { ... }
            collectWhileInState { ... }
            onEnterStartStateMachine { ... }
            onActionStartStateMachine { ... }
            condition { ... }
            untilIdentityChanged { ... }
        }
    }

    inState<Child3> {
        onEnter { ... }
        onAction { ... }
        collectWhileInState { ... }
        onEnterStartStateMachine { ... }
        onActionStartStateMachine { ... }
        condition { ... }
        untilIdentityChanged { ... }
    }
}
```
In both cases `spec` would have every method that `inState` has scoped to the state machine's state class. In the last version `spec` and `inState` would basically be both and `InStateBlockBuilder` with the ability to nest `inState` inside one another. Like mentioned above the advantage would be that you can more easily see how certain blocks run together, the disadvantages would be risk of nesting getting too deep and using the top level actions too much (although that is already possible with `inState<Parent>`)
