### ISSUE TITLE
Test dependencies packaged into jvmMain

### ISSUE THREAD

**Issue by ychescale9** [freeletics/FlowRedux#54]
It appears that `com.freeletics.flow.test:test:0.0.2-SNAPSHOT` (and a few other test libraries) are included in `com.freeletics.flowredux:dsl:0.2.1` as a runtime dependency.

Are there any reasons the following dependencies are not defined in the `jvmTest` configuration?

https://github.com/freeletics/FlowRedux/blob/fde227e87ab8e3441b885f66a8f551323e56a72a/dsl/build.gradle#L48-L52

**Comment by sockeqwe** [comment]
No, that was just a mistake.
Thanks for pointing it out. 

Will fix that.

**Comment by sockeqwe** [comment]
Is fixed. 0.3.0 will rollout soon solving this.
