### ISSUE TITLE
[Question] Dead lock in dispatching multiple actions to ORDERED OnAction statement

### ISSUE THREAD

**Issue by xiaozhikang0916** [freeletics/FlowRedux#608]
I made a simple snippst to reproduce my issue on 1.2.0:

https://gist.github.com/xiaozhikang0916/6f4cf768e547d48a30479a9c13547ddb

It comes to a dead locking situation and the state machine becomes unable to handle any up coming action.

And I found some ways to make it works:

1. Remove all the `executionPolicy = ExecutionPolicy.ORDERED` statement in the statemachine dsl, or
2. Dispatch ActionA before ActionB, to meet the order of OnAction statement in the dsl.

I wonder why the order of statement matters here.

This code works fine in 1.1.0

**Comment by gabrielittner** [comment]
Thanks for the reproducer, I'll take a look

**Comment by xiaozhikang0916** [comment]
Any update about it?

**Comment by gabrielittner** [comment]
The bug should be fixed, you can already try out the latest snapshot and I'll cut a release in the next days.
