### ISSUE TITLE
1.2.0 seems to be broken regarding iOS

### ISSUE THREAD

**Issue by muellnes** [freeletics/FlowRedux#626]
Could not find "mad.state-machine:runtime" in [.konan/klib, .konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/common, .konan/kotlin-native-prebuilt-macos-aarch64-1.9.21/klib/platform/ios_simulator_arm64]

**Comment by gabrielittner** [comment]
Closing until there is more actionable information
